const fs = require('fs');

const content = [
  "import { createFileRoute } from '@tanstack/react-router';",
  "import { useMemo } from 'react';",
  "",
  "import Header from '../components/Header';",
  "import LearningPath, { LearningUnit, UnitStatus } from '../components/LearningPath';",
  "import { useUnits } from '../hooks/useUnits';",
  "",
  "function HomePage() {",
  "  const { units: unitsData, loading, error } = useUnits()",
  "",
  "  // Mapear unidades do banco para o formato esperado pelo LearningPath",
  "  const units: LearningUnit[] = useMemo(() => {",
  "    if (!unitsData.length) return []",
  "",
  "    let previousUnitCompleted = true",
  "",
  "    return unitsData.map((unit) => {",
  "      const allLessonsCompleted =",
  "        unit.lessons.length > 0 && unit.lessons.every((lesson) => lesson.completed)",
  "",
  "      const status: UnitStatus = allLessonsCompleted",
  "        ? 'completed'",
  "        : previousUnitCompleted",
  "        ? 'available'",
  "        : 'locked'",
  "",
  "      previousUnitCompleted = allLessonsCompleted",
  "",
  "      return {",
  "        id: unit.id,",
  "        status,",
  "        unitData: unit,",
  "      }",
  "    })",
  "  }, [unitsData])",
  "  return (",
  '    <main className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(167,139,250,0.18),_transparent_28%),linear-gradient(180deg,#7c3aed_0%,#5b21b6_55%,#2d0f65_100%)] px-6 py-6 sm:px-8 lg:px-10">',
  "      <Header />",
  "",
  '      <div className="mt-5">',
  '        <div className="w-full min-h-[120px] max-h-[130px] rounded-[18px] bg-gradient-to-r from-[#a78bfa] to-[#7c3aed] border-b-[6px] border-[#5b21b6] p-[22px] cursor-pointer ">',
  '          <div className="flex h-full flex-col justify-center">',
  '            <span className="text-white font-bold text-[0.72rem] tracking-[0.18em] uppercase mb-2.5">',
  "              COME\u00c7AR UNIDADE",
  "            </span>",
  '            <h1 className="text-white font-extrabold text-[40px] leading-[1.05]">',
  "              Fundamentos de JavaScript",
  "            </h1>",
  "          </div>",
  "        </div>",
  "      </div>",
  "",
  "      {/* Loading state */}",
  "      {loading && (",
  '        <div className="flex justify-center py-12">',
  '          <p className="text-white text-lg">Carregando unidades...</p>',
  "        </div>",
  "      )}",
  "",
  "      {/* Error state */}",
  "      {error && (",
  '        <div className="flex justify-center py-12">',
  '          <p className="text-red-300 text-lg">Erro ao carregar unidades: {error}</p>',
  "        </div>",
  "      )}",
  "",
  "      {/* Learning path abaixo do banner */}",
  "      {!loading && !error && (",
  "        <LearningPath",
  "          units={units}",
  "          onUnitClick={(unit, idx) => {",
  "            console.log('unit click', unit, idx)",
  "          }}",
  "        />",
  "      )}",
  "    </main>",
  "  )",
  "}",
  "",
  "export const Route = createFileRoute('/')({",
  "  component: HomePage,",
  "});",
  ""
].join('\n');

fs.writeFileSync('src/routes/index.tsx', content, 'utf8');
console.log('File written successfully!');
