const fs = require('fs');

const lines = [];
lines.push("import { createFileRoute } from '@tanstack/react-router';");
lines.push("import { useMemo } from 'react';");
lines.push("");
lines.push("import Header from '../components/Header';");
lines.push("import LearningPath, { LearningUnit, UnitStatus } from '../components/LearningPath';");
lines.push("import { useUnits } from '../hooks/useUnits';");
lines.push("");
lines.push("function HomePage() {");
lines.push("  const { units: unitsData, loading, error } = useUnits()");
lines.push("");
lines.push("  // Mapear unidades do banco para o formato esperado pelo LearningPath");
lines.push("  const units: LearningUnit[] = useMemo(() => {");
lines.push("    if (!unitsData.length) return []");
lines.push("");
lines.push("    let previousUnitCompleted = true");
lines.push("");
lines.push("    return unitsData.map((unit) => {");
lines.push("      const allLessonsCompleted =");
lines.push("        unit.lessons.length > 0 && unit.lessons.every((lesson) => lesson.completed)");
lines.push("");
lines.push("      const status: UnitStatus = allLessonsCompleted");
lines.push("        ? 'completed'");
lines.push("        : previousUnitCompleted");
lines.push("        ? 'available'");
lines.push("        : 'locked'");
lines.push("");
lines.push("      previousUnitCompleted = allLessonsCompleted");
lines.push("");
lines.push("      return {");
lines.push("        id: unit.id,");
lines.push("        status,");
lines.push("        unitData: unit,");
lines.push("      }");
lines.push("    })");
lines.push("  }, [unitsData])");
lines.push("  return (");
lines.push('    <main className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(167,139,250,0.18),_transparent_28%),linear-gradient(180deg,#7c3aed_0%,#5b21b6_55%,#2d0f65_100%)] px-6 py-6 sm:px-8 lg:px-10">');
lines.push("      <Header />");
lines.push("");
lines.push('      <div className="mt-5">');
lines.push('        <div className="w-full min-h-[120px] max-h-[130px] rounded-[18px] bg-gradient-to-r from-[#a78bfa] to-[#7c3aed] border-b-[6px] border-[#5b21b6] p-[22px] cursor-pointer ">');
lines.push('          <div className="flex h-full flex-col justify-center">');
lines.push('            <span className="text-white font-bold text-[0.72rem] tracking-[0.18em] uppercase mb-2.5">');
lines.push("              COMEÇAR UNIDADE");
lines.push("            </span>");
lines.push('            <h1 className="text-white font-extrabold text-[40px] leading-[1.05]">');
lines.push("              Fundamentos de JavaScript");
lines.push("            </h1>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      /* Loading state */");
lines.push("      {loading && (");
lines.push('        <div className="flex justify-center py-12">');
lines.push('          <p className="text-white text-lg">Carregando unidades...</p>');
lines.push("        </div>");
lines.push("      )}");
lines.push("");
lines.push("      /* Error state */");
lines.push("      {error && (");
lines.push('        <div className="flex justify-center py-12">');
lines.push('          <p className="text-red-300 text-lg">Erro ao carregar unidades: {error}</p>');
lines.push("        </div>");
lines.push("      )}");
lines.push("");
lines.push("      /* Learning path abaixo do banner */");
lines.push("      {!loading && !error && (");
lines.push("        <LearningPath");
lines.push("          units={units}");
lines.push("          onUnitClick={(unit, idx) => {");
lines.push("            console.log('unit click', unit, idx)");
lines.push("          }}");
lines.push("        />");
lines.push("      )}");
lines.push("    </main>");
lines.push("  )");
lines.push("}");
lines.push("");
lines.push("export const Route = createFileRoute('/')({");
lines.push("  component: HomePage,");
lines.push("});");
lines.push("");

const content = lines.join('\n');
fs.writeFileSync('src/routes/index.tsx', content, 'utf8');
console.log('File written successfully');
