const fs = require("fs");

const lines = [];
lines.push('import { useEffect, useState } from "react";');
lines.push('import { useNavigate } from "@tanstack/react-router";');
lines.push('import loaderImage from "../assets/images/devlingo-loader.png";');
lines.push("");
lines.push("export default function LoadingScreen() {");
lines.push('  const [isVisible, setIsVisible] = useState(true);');
lines.push('  const [isFading, setIsFading] = useState(false);');
lines.push("  const navigate = useNavigate();");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    const visibleTimer = window.setTimeout(() => {");
lines.push("      setIsFading(true);");
lines.push("      const fadeTimer = window.setTimeout(() => {");
lines.push("        setIsVisible(false);");
lines.push("        navigate({ to: '/signin' });");
lines.push("      }, 700);");
lines.push("      return () => window.clearTimeout(fadeTimer);");
lines.push("    }, 2000);");
lines.push("");
lines.push("    return () => window.clearTimeout(visibleTimer);");
lines.push("  }, [navigate]);");
lines.push("");
lines.push("  if (!isVisible) {");
lines.push("    return null;");
lines.push("  }");
lines.push("");
lines.push("  return (");
lines.push('    <div');
lines.push('      className={`fixed inset-0 z-[9999] flex items-center justify-center bg-purple-950/95 transition-opacity duration-700 ${isFading ? "opacity-0" : "opacity-100"} pointer-events-auto`}');
lines.push("    >");
lines.push('      <div className="relative flex flex-col items-center gap-6 rounded-[2rem] bg-white/10 border border-white/20 px-8 py-10 shadow-2xl backdrop-blur-xl">');
lines.push('        <div className="flex h-28 w-28 items-center justify-center rounded-full bg-gradient-to-br from-violet-500 via-fuchsia-500 to-indigo-500 shadow-xl">');
lines.push("          <img");
lines.push("            src={loaderImage}");
lines.push('            alt="Devlingo loader"');
lines.push('            className="h-20 w-20 object-contain animate-float"');
lines.push("          />");
lines.push("        </div>");
lines.push('        <div className="text-center">');
lines.push('          <h1 className="text-4xl font-extrabold text-white">Devlingo</h1>');
lines.push('          <p className="mt-2 text-sm text-white/75">Carregando o aplicativo... aguarde um momento.</p>');
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  );");
lines.push("}");
lines.push("");

fs.writeFileSync("src/components/LoadingScreen.tsx", lines.join("\n"), "utf8");
console.log("FIXED OK");

